### ISSUE TITLE
Downloading multiple versions requires restart

### ISSUE THREAD

**Issue by jw3** [jw3/example-daffodil-vscode#10]
v0.0.2

1. Start debug
2. Enter a version that needs downloaded
3. Wait for download
4. Enter same version (see #9)
5. Run debug ... end debug
6. Start new debug
7. Enter a new version that will need downloaded
8. Get error
```
> Executing task: ./daffodil-debugger-0.0.3/bin/da-podil <

/bin/bash: ./daffodil-debugger-0.0.3/bin/da-podil: No such file or directory
The terminal process "/bin/bash '-c', './daffodil-debugger-0.0.3/bin/da-podil'" failed to launch (exit code: 127).

Press any key to close the terminal.
```

**Comment by Shanedell** [comment]
Most recent push to master and release v0.0.3 fixes this issue
