### ISSUE TITLE
Debug session doesn't connect to launched backend

### ISSUE THREAD

**Issue by arosien** [jw3/example-daffodil-vscode#111]
Fresh install of 0.0.14:

- Open `jpeg.dfdl.xsd` in VSCode, choose menu "Daffodil Debug: Debug File".
- Backend launches waiting for connection from extension. Nothing connects, backend exits after 10 seconds.

Will try to reproduce locally at the HEAD of the main branch.

**Comment by arosien** [comment]
I'm looking into this one...

**Comment by arosien** [comment]
This code executes:

```typescript
      if (config.data.includes('${command:AskForDataName}')) {
        config.data = await vscode.commands.executeCommand(
          'extension.dfdl-debug.getDataName'
        )
      }
```

but sets `config.data` to `''`.

**Comment by arosien** [comment]
It is the caching thing being tripped:

```
➜  example-daffodil-vscode git:(master) ✗ ls -l /Users/arosien/Library/Application\ Support/dapodil/.programFile
-rw-r--r--  1 arosien  staff  0 Aug 27 11:44 /Users/arosien/Library/Application Support/dapodil/.programFile
```

Zero length file stops the debugging:

```typescript
if (programFile === '') {
  stopDebugging()
  return ''
}
```

**Comment by Shanedell** [comment]
So I can update this the reason for the caching as it was the way so that if the user uses both `${command:AskForProgramName}` and `${command:AskForDataName}` that if they don't select a file for `AskForProgramName` that the debugger stops. However I did not catch that it breaks the `Debug File` and `Run File` so I am looking into how to make sure it is only happens on certain cases

**Comment by arosien** [comment]
@Shanedell i think i have the fix: `getProgramName` shouldn't save an empty program name in the cache. I'll post a PR.

**Comment by Shanedell** [comment]
@arosien Oh okay I think I see what you are saying

**Comment by arosien** [comment]
Well, I need to think it through... :)

**Comment by Shanedell** [comment]
@arosien Nevermind my previous comment it is needed as the `stopDebugging` on selecting a programFile does not actually cause a full stop

**Comment by arosien** [comment]
I think the real issue is that once the choice of program or data file is persisted, it doesn't get cleared. Now I'm not sure why it is persisted in the first place.

**Comment by Shanedell** [comment]
@arosien So one thing I remember being a requirement was for the extension to not prompt for a dataFile if no programFile was selected, this was the purpose for the caching. So I we may want to put that back into that check (I can do it here in a sec) because as I was running yours it stills prompts me for a dataFile when I select nothing for a programFile. So I will just add some better checking into the caching to make sure the prior issues are resolved as well.

**Comment by arosien** [comment]
> @arosien So one thing I remember being a requirement was for the extension to not prompt for a dataFile if no programFile was selected, this was the purpose for the caching. So I we may want to put that back into that check (I can do it here in a sec) because as I was running yours it stills prompts me for a dataFile when I select nothing for a programFile. So I will just add some better checking into the caching to make sure the prior issues are resolved as well.

That's very strange, I don't see how the code allows the data dialog to appear after an empty program is selected, but it does happen.

**Comment by arosien** [comment]
Ah, it's appears there's hooks in the debugger extension `package.json` that launch commands:

```json
        "variables": {
          "AskForProgramName": "extension.dfdl-debug.getProgramName",
          "AskForDataName": "extension.dfdl-debug.getDataName"
        }
```

So perhaps our code shouldn't do this substitution "manually"?

**Comment by arosien** [comment]
> Ah, it's appears there's hooks in the debugger extension `package.json` that launch commands:
> 
> ```json
>         "variables": {
>           "AskForProgramName": "extension.dfdl-debug.getProgramName",
>           "AskForDataName": "extension.dfdl-debug.getDataName"
>         }
> ```
> 
> So perhaps our code shouldn't do this substitution "manually"?

Oh, I'm guessing if this is used then the backend launches too soon while the dialogs are waiting to be filled in.

**Comment by Shanedell** [comment]
Yeah them being inducted via `package.json` is why `getDataName` will still get execute so I am working on getting a good work around here.

**Comment by arosien** [comment]
Mutable data is evil.

**Comment by Shanedell** [comment]
@arosien That fix you put in looks good going to merge it in here I just had to push up one commit for lint issues
