### ISSUE TITLE
Reference the MVP as 1.0

### ISSUE THREAD

**Issue by jw3** [jw3/example-daffodil-vscode#124]
Rather than 0.1.0 we are going to target 1.0

**Comment by arosien** [comment]
I like this, although I'm concerned that the ASF has some sort of regulations about version naming schemes, like "you can't release a 1.0 until you've had an X", or something like that. I'll look into it and comment here.

**Comment by arosien** [comment]
Per Mike and Steve, 1.0(.0) is ok. Looking at other extensions, the majority use 3 numerals.
