### ISSUE TITLE
Add Apache licenses to header on all our files and update the top level license file

### ISSUE THREAD

**Issue by jw3** [jw3/example-daffodil-vscode#126]

**Comment by arosien** [comment]
https://github.com/sbt/sbt-header can be used to do this automatically to Scala files, and possibly as a build check during CI.

**Comment by arosien** [comment]
Also need to replace the existing, incorrect `LICENSE.txt` with Apache 2.0. Use this issue, or have a separate one?

**Comment by arosien** [comment]
> https://github.com/sbt/sbt-header can be used to do this automatically to Scala files, and possibly as a build check during CI.

I can do this part quick.

**Comment by jw3** [comment]
Sounds good.  Yeah just do all Apache 2.0 licenses in this one.

**Comment by arosien** [comment]
Who should the copyright be listed as? The real names of @jw3, @arosien, @Shanedell, @rthomas320, @mangusj?

**Comment by arosien** [comment]
https://github.com/jw3/example-daffodil-vscode/tree/issue/126-licenses-for-scala-files

**Comment by jw3** [comment]
For the ts files
https://yarnpkg.com/package/license-check
https://github.com/awjh/license-check-and-add

**Comment by jw3** [comment]
https://www.apache.org/legal/src-headers.html#headers

**Comment by jw3** [comment]
Updated all the typescript files to have similar header as the scala files, with addition of @Shanedell

**Comment by jw3** [comment]
Added a txt file for the snippets json.   Read on stack exchange that would be a way to go about that in a non-commentable file

https://opensource.stackexchange.com/a/203
