### ISSUE TITLE
Review test data

### ISSUE THREAD

**Issue by jw3** [jw3/example-daffodil-vscode#132]
The schema and jpg need reviewed for licensing issues.  Replacing with a compatible set of sch and data from Daffodil as needed.

**Comment by arosien** [comment]
Or just remove them from this repo.

**Comment by jw3** [comment]
Yep I'm good with that

**Comment by jw3** [comment]
These were trimmed out.  Can be PR'd back in to the new repo after we identify which test data files and sample workspace files are ideal to maintain alongside the code.
