### ISSUE TITLE
Failed to launch 0.4

### ISSUE THREAD

**Issue by arosien** [jw3/example-daffodil-vscode#15]
I installed v0.4 of the extension locally, and used the provided launch.json:

```
...
{
  "type": "dfdl",
  "request": "launch",
  "name": "Debug JPEG",
  "program": "${workspaceFolder}/jpeg.dfdl.xsd",
  "data": "${workspaceFolder}/works.jpg",
  "stopOnEntry": true,
  "trace": false,
  "debugServer": 4711
}
```

At the Daffodil version prompt I enter `3.1.0` but then I get a popup error dialog that says

> Unexpected HTTP response: 404

I can't find any other output. Any ideas?

**Comment by jw3** [comment]
The version there corresponds to the debugger backend, so use `0.0.5` for the latest.

**Comment by Shanedell** [comment]
@arosien you need to enter in the release version you wish to use from the `example-daffodil-debug` so any release version out of on that repo should be good. 

Expected input is either something like `0.0.5` or `v0.0.5`.

Hope this helps.

**Comment by arosien** [comment]
@Shanedell oh, the `example-daffodil-debug` version! OOPS. Thanks!
