### ISSUE TITLE
Don't hardcode prefix on version string

### ISSUE THREAD

**Issue by jw3** [jw3/example-daffodil-vscode#2]
Don't prefixed user specified version with a "v", user should enter the exact version string.

**Comment by jw3** [comment]
I see this is due to the prefix mismatch between the releases and the packaging.

**Comment by Shanedell** [comment]
The PR attached will allow the user to enter in both `v0.0.1` and `0.0.1` and it will work the same. If the the releases of the debugger file names to be something like `daffodil-debugger-v0.0.5` then all that is need is to remove the `.substring(1)` attached to `dapodilDebuggerVersion` and now it will work with that. However for the input of task to run the debugger you string must enter a version `0.0.1` and will need to unless the zip file names end up getting changed.
