### ISSUE TITLE
Launch fails but then mock markdown debug session starts

### ISSUE THREAD

**Issue by arosien** [jw3/example-daffodil-vscode#29]
When I install the extension (version 0.0.6), I don't yet know how to start a debug session. I guessed that I need to make a launch configuration, so I added

```json
    {
      "type": "dfdl",
      "request": "launch",
      "name": "Ask for file name",
      "program": "${workspaceFolder}/src/main/resources/jpeg.dfdl.xsd",
      "data": "${workspaceFolder}/src/main/resources/works.jpg",
      "stopOnEntry": true
    }
```

When I run this from VS Code, I choose (backend) version 0.0.6, an error flashes in the Terminal, but then the Terminal exits before I can read what happened. I can't find the error message in any of the Output buffers, so I'm a bit stuck.

There's some launch problem, but _then_ the (fake) markdown debugger starts from the default code in the mock extension. Oh noes!

**Comment by Shanedell** [comment]
@arosien is this what your full `.vscode/launch.json` looks like?
```
{
	"version": "0.2.0",
	"configurations": [
		{
                    "type": "dfdl",
                    "request": "launch",
                    "name": "Ask for file name",
                    "program": "${workspaceFolder}/src/main/resources/jpeg.dfdl.xsd",
                    "data": "${workspaceFolder}/src/main/resources/works.jpg",
                    "stopOnEntry": true
                 }
	]
}
```
I tested with this configuration in the `example-daffodil-debug` repo and was able to select `v0.0.6` and have it launch properly.

**Comment by Shanedell** [comment]
@arosien
I believe the error you were seeing was because you did add in the `debugServer: 4711` so the extension never attached to the debugger instance running. 

This would cause the runner to keep running in the background until you manually kill the process.

So whenever you would try to run the debug session again it would try to run another instance of the debugger while it was already running so that error you couldn't see was about the address port already being in use.

**Comment by jw3** [comment]
> I guessed that I need to make a launch configuration

Thinking about how we debug other software, we dont hand craft launch configs #30

**Comment by arosien** [comment]
No, I have exactly this (no `debugServer: 4711` line):

```
{
      "type": "dfdl",
      "request": "launch",
      "name": "Ask for file name",
      "program": "${workspaceFolder}/src/main/resources/jpeg.dfdl.xsd",
      "data": "${workspaceFolder}/src/main/resources/works.jpg",
      "stopOnEntry": true
    }
```

**Comment by arosien** [comment]
> > I guessed that I need to make a launch configuration
> 
> Thinking about how we debug other software, we dont hand craft launch configs #30

My expectation is that I have a `.dfdl.xsd` file in focus, and I open the Command Palette (Shift-Command-P), type `daffodil`, and would see a menu item to debug a Daffodil schema. Then there would be some dialog to choose the data file to use with the schema.

**Comment by arosien** [comment]
> This would cause the runner to keep running in the background until you manually kill the process.
> 
> So whenever you would try to run the debug session again it would try to run another instance of the debugger while it was already running so that error you couldn't see was about the address port already being in use.

You're right, the error I'm seeing flashed is due to an existing Daffodil backend running and the port is conflicting.

If I ensure it isn't running, I get a proper debug launch, but the `DAPodil` process doesn't seem to be exiting if the parse succeeds or if I hit the "stop" control. I'll start a new issue for that.
