### ISSUE TITLE
Autogenerated launch configurations

### ISSUE THREAD

**Issue by jw3** [jw3/example-daffodil-vscode#30]
Is there a pattern in VS Code to create a launch configuration for a file.  Eg. right click on a schema, select debug, and if a launch config doesn't exist for that schema one is created from a template for the launch?

**Comment by Shanedell** [comment]
@jw3 I believe you have to make the initial file and add this to it
```
{
    "version": "0.2.0",
    "configurations": [

    ]
}
```
Once you start typing `Daffodil` inside of configuration there should be an option, `Daffodil Debug: Launch`, you can select. Once selected it will autocreate the configuration. I thought I updated it to have everything needed but I can update it to have other things like the debugServer, which I believe is the main one that is missing

**Comment by jw3** [comment]
https://github.com/jw3/example-daffodil-vscode/issues/29#issuecomment-865151444

> My expectation is that I have a .dfdl.xsd file in focus, and I open the Command Palette (Shift-Command-P), type daffodil, and would see a menu item to debug a Daffodil schema. Then there would be some dialog to choose the data file to use with the schema.
