### ISSUE TITLE
Infoset diff view

### ISSUE THREAD

**Issue by jw3** [jw3/example-daffodil-vscode#35]
Add a view that accepts a diff event and displays the content.

**Comment by kirkejohnson** [comment]
I believe that InfoSets are either XML or JSON, although I'm not sure that JSON is currently supported.

This would apply for debugging a parse operation, where the InfoSet is effectively the output of the operation.
For an unparse operation, the input to the operation is the InfoSet and the output is a file.

**Comment by jw3** [comment]
The goal here would be to use the XML infoset and simply show a diff between the previous state and the current state, and would be limited to parse operations for the initial MVP.

There was something similar done in the early standalone debugger prototype.  See the bottom right text view, https://vimeo.com/541195103

Extremely large infosets may pose a challenge, but focusing on reasonably sized ones initially should be straight forward.
