### ISSUE TITLE
Improved documentation

### ISSUE THREAD

**Issue by jw3** [jw3/example-daffodil-vscode#39]
- GIF how-to images
- clean up things that dont apply

**Comment by jw3** [comment]
Would be good to browse other extensions for documentation examples, the Python extension for example effectively makes use of GIFs.

**Comment by arosien** [comment]
I use the https://marketplace.visualstudio.com/items?itemName=arcsine.chronicler extension to generate animated gifs.

**Comment by jw3** [comment]
Thinking about the things to document with an animation
- Optionally creating the launch.json when one is not present
- Launching the debugger and selecting a version
- Opening of any custom views (like hex view, infoset view, etc)
- Evaluating expressions on debug console

**Comment by jw3** [comment]
Images from this issue back the wiki page at https://github.com/jw3/example-daffodil-vscode/wiki

The goal here was to avoid sending a bunch of binaries into the repo to link in the readme.

Eventually when the repo is in the new org these gifs can be uploaded to a stable location and maintained.  Until then lets just reference the wiki and keep the readme and repo clean of binaries and links to deprecated github projects.
