### ISSUE TITLE
Inputstream view

### ISSUE THREAD

**Issue by jw3** [jw3/example-daffodil-vscode#45]
What "view" means here is still undefined in 0.1.0.  Keeping in mind the scope here and that we want to deliver an MVP, this could be limited to a simple text view or it could be the more full featured hex viewer.

This post is interesting https://github.com/jw3/example-daffodil-vscode/issues/7#issuecomment-856877857

**Comment by kirkejohnson** [comment]
For a parse operation I presume this would be the input file being parsed.  If so this view should support seeing that file in a number of different format/encodings:  binary/hex, ASCII, Unicode (UTF-8 & UTF-16, minimally).

For an unparse operation I assume this would be the InfoSet.

**Comment by arosien** [comment]
I think the backend will need to send a custom event that details the current position within the data file.
