### ISSUE TITLE
Store downloaded files elsewhere

### ISSUE THREAD

**Issue by jw3** [jw3/example-daffodil-vscode#5]
Keeping downloads in the project dir is not ideal, but was nice for a quick turn on this.  For a 0.1 we need to investigate a portable solution to this problem.

In Rust there is https://github.com/dirs-dev/dirs-rs which says

> The library provides the location of these directories by leveraging the mechanisms defined by
> - the [XDG base directory](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html) and the [XDG user directory](https://www.freedesktop.org/wiki/Software/xdg-user-dirs/) specifications on Linux and Redox
> - the [Known Folder](https://msdn.microsoft.com/en-us/library/windows/desktop/dd378457.aspx) API on Windows
> - the [Standard Directories](https://developer.apple.com/library/content/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html#//apple_ref/doc/uid/TP40010672-CH2-SW6) guidelines on macOS

**Comment by arosien** [comment]
I was looking at [another extension](https://github.com/vadimcn/vscode-lldb/blob/master/extension/install.ts#L52) and they use `os.tmpdir` to store the downloaded stuff.
