### ISSUE TITLE
Configured debug type 'dfdl' is not supported.

### ISSUE THREAD

**Issue by arosien** [jw3/example-daffodil-vscode#54]
I upgraded the extension from 0.0.6 to 0.0.7 and can't seem to launch a debug session. I get a popup that says:

> Configured debug type 'dfdl' is not supported.

My launch config is:

```
{
      "type": "dfdl",
      "request": "launch",
      "name": "Daffodil: jpeg.dfdl.xsd/works.jpg",
      "program": "${workspaceFolder}/src/main/resources/jpeg.dfdl.xsd",
      "data": "${workspaceFolder}/src/main/resources/works.jpg",
      "stopOnEntry": true,
      "debugServer": 4711
},
```

**Comment by Shanedell** [comment]
@arosien Did you restart VSCode after upgrading? Sometime if you go to the extension list and check the `Daffodil Debug` extension it may say `Reload Required`. You also have multiple instances of the `Daffodil Debug` installed if you did uninstall the previous version then install the latest. Other than that I am aware of what the issue could be as I could not fully duplicate the issue myself

**Comment by arosien** [comment]
I did have an upgrade issue, I'll re-repro, thanks!

**Comment by arosien** [comment]
Local issue with my VSCode.
