### ISSUE TITLE
Reopen hex view

### ISSUE THREAD

**Issue by jw3** [jw3/example-daffodil-vscode#57]
After the hex view is closed it should be able to be opened without restarting the debug.

**Comment by jw3** [comment]
`ctrl + shift + t` seems to reopen this

**Comment by arosien** [comment]
> `ctrl + shift + t` seems to reopen this

That reopens the most recently closed file, but there's no specific way of opening the hex view itself. Perhaps that could be an extension-added "command"?

**Comment by jw3** [comment]
Yes, it should have a command
- user might not want it to open automatically
- user might close it, then open and close 10 other files, so to get it back you have to ctrl shift T 10 times

Can see a reference impl in #66
