### ISSUE TITLE
Hex view opens again after restarting the workspace

### ISSUE THREAD

**Issue by jw3** [jw3/example-daffodil-vscode#58]
I would expect the hex view to be cleaned up after closing the debug session.  It is not cleaned up and even returns after workspace restart.

### Steps to reproduce
1. start a debug, hex view displayed
2. close ide
3. open ide
4. hex view is displayed

**Comment by Shanedell** [comment]
@jw3 This is kind of IDE functionality that if a document is not closed when IDE is closed it will reopen it once the IDE reopens. But I am updating the debugger to auto close the hex viewer once no more data positions are being sent over then if you start a debug session it will check if the hex-file is opened if it is it will be closed then reopened once it is remade
