### ISSUE TITLE
Have Daffodil 3.1.0 published as GitHub release

### ISSUE THREAD

**Issue by jw3** [jw3/example-daffodil-vscode#59]
We will need the 3.1.0 release published to the Daffodil page to complete the 0.1.0 release.

**Comment by arosien** [comment]
I'm not sure why this is a requirement, given the current state of how the debugger backend is built. Are you imagining the extension downloading the Daffodil release itself, instead of our debugger artifact (that includes it)?

**Comment by jw3** [comment]
> Are you imagining the extension downloading the Daffodil release itself, instead of our debugger artifact (that includes it)?

Yes, and this issue could get bumped off of 0.1.0 depending on how the packaging shakes out.

**Comment by jw3** [comment]
No longer valid, see #76
