### ISSUE TITLE
Hex View Select Clarification

### ISSUE THREAD

**Issue by Shanedell** [jw3/example-daffodil-vscode#65]
![hex-view-pos](https://user-images.githubusercontent.com/32347414/128377886-dc3717b4-9754-46cc-8033-da91becaf94b.png)

So this has been fixed but I want to sure to clarify that we need to show the byte selected so if the `bytePos1b` is 7 the selection should be `4A` correct? @arosien so something that looks like this

![Screen Shot 2021-08-05 at 11 44 05 AM](https://user-images.githubusercontent.com/32347414/128380176-4a308363-7a02-4b0e-bd19-415a0868ecf2.png)

**Comment by arosien** [comment]
`4A` is correct!
