### ISSUE TITLE
Add custom text view

### ISSUE THREAD

**Issue by jw3** [jw3/example-daffodil-vscode#7]
Demonstrate adding a new view which is a read-only text display.

**Comment by arosien** [comment]
See also https://github.com/jw3/example-daffodil-debug/issues/13#issuecomment-841532375:

> Alternatively, the infoset could be a separate "virtual" document: https://code.visualstudio.com/api/extension-guides/virtual-documents.

which I'm assuming will be the impl.

**Comment by arosien** [comment]
I'm unsure which "channel" this data would come from. Some possibilities:

- send custom events via DAP, which (somehow) can be intercepted without interference with the VS Code debugger impl.
- use a different socket + protocol to talk to the debugee (daffodil)
- ?

**Comment by arosien** [comment]
Here's an example of an extension that has a custom view for displaying debug information: https://github.com/vadimcn/vscode-lldb/blob/cf886f402476517379f5d9b43c89639a15e3b793/extension/htmlView.ts#L13

It's a "native" debugger that has a custom "disassembly" view, which is very similar to what we're doing. This view is, afaict, just HTML that the debugger generates.

!()[https://github.com/vadimcn/vscode-lldb/raw/cf886f402476517379f5d9b43c89639a15e3b793/images/disasm.png]

**Comment by arosien** [comment]
Here's an alternative: "loaded scripts". The debugger can provide a collection of associated sources and their contents, I believe the mime-type determines how they are displayed(?). There could be a "data" source and an "infoset" source.

https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_access-loaded-scripts
