### ISSUE TITLE
Ensure version in package.json matches latest tag.

### ISSUE THREAD

**Issue by arosien** [jw3/example-daffodil-vscode#82]
We should be using [`npm version`] for releases, as it can manage both the git tag and the version specified in the `package.json` file. Currently the `package.json` file has version `0.7.0`, but the latest tag is `v0.0.9`.

**Comment by jw3** [comment]
closed in #76 by adding a check to the workflow that guards against a vsix being built with a package json version that does not match the git tag version.

https://github.com/jw3/example-daffodil-vscode/blob/master/.github/workflows/release.yml#L22-L24
