### ISSUE TITLE
Determine JRE requirements and document in the installation instructions

### ISSUE THREAD

**Issue by jw3** [jw3/example-daffodil-vscode#94]
I assume >= 1.8 ?  Should verify.

**Comment by jw3** [comment]
User reported a `NoSuchMethod` exception on `Path.of`.

`Path.of` was added at [Java 11](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/nio/file/Path.html#of(java.net.URI)).

User is running Java 8.

**Comment by jw3** [comment]
I tried passing `-source 11`, `-target 8` to javac, figured compile would fail, it didnt, but did fail at runtime again.

**Comment by arosien** [comment]
![image](https://user-images.githubusercontent.com/31163/131869550-a17c4cac-ab60-48de-a2d9-22ec2a19a5ae.png)

**Comment by jw3** [comment]
Cleaned up all usage of > JDK 8 features.  The above error is the next in the sequence of errors.

**Comment by jw3** [comment]
Looking for the minimum java for https://github.com/microsoft/java-debug...

**Comment by jw3** [comment]
No, but we have explicit depend on java-debug.

Looks like java-debug minimum is 11, but I didnt see it explicitly stated anywhere else.

**Comment by arosien** [comment]
java-debug appears to require 8: https://github.com/microsoft/java-debug/blob/main/com.microsoft.java.debug.core/pom.xml#L31

I think the problem is the "Malformed class name" is a Scala + JDK bug that requires JDK > 8.

**Comment by jw3** [comment]
Ok, should test on 9 so it can be documented accurately.

It's unfortunate though Daffodil is at 1.8 and this will be > than that.

**Comment by arosien** [comment]
I can restructure the Scala code to avoid the bug, but it's not a 1-day job.

**Comment by jw3** [comment]
It would be nice, with that fix and the couple of changes to drop the > 1.8 features we can go back to 1.8.

For now we can push ahead with 0.1.0 prep and just say support back to 1.8 is coming, but is WIP.

**Comment by arosien** [comment]
JRE 11 is documented as required. Subsequent work filed at #136.
